config/routes.rb
Servermgr::Application.routes.draw do
  resources :servers

  match '/auth/:provider/callback', :via => :get, :to => 'sessions#create'
  match '/auth/failure', :via => :get, :to => 'sessions#failure'
  get 'logout', :to => 'sessions#destroy'
  match 'bad' => 'sessions#bad', :via => :get, :as => :bad

  get 'home' => 'home#index', :as => :home
  get 'about' => 'home#about', :as => :about
  get 'contact' => 'home#contact', :as => :contact

  resources :cloud_accounts
  resources :sessions

  resources :users, :id => /[a-z0-9-]*/

  root :to => 'welcome#index'

  

end

app/models/server.rb
class Server < ActiveRecord::Base
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :set_server, only: [:show, :edit, :update, :destroy]

  # GET /servers
  # GET /servers.json
  def index
    @servers = Server.all
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
  end

  # GET /servers/new
  def new
    @server = Server.new
  end

  # GET /servers/1/edit
  def edit
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(server_params)

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, notice: 'Server was successfully created.' }
        format.json { render action: 'show', status: :created, location: @server }
      else
        format.html { render action: 'new' }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servers/1
  # PATCH/PUT /servers/1.json
  def update
    respond_to do |format|
      if @server.update(server_params)
        format.html { redirect_to @server, notice: 'Server was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server.destroy
    respond_to do |format|
      format.html { redirect_to servers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_server
      @server = Server.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def server_params
      params.require(:server).permit(:customer_name, :customer_email, :server_name, :server_id, :server_type, :server_public_ipaddress, :server_private_ipaddress, :server_account, :server_password, :server_status)
    end
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/_form.html.erb
<%= form_for @server, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :customer_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :customer_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :customer_email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :customer_email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :server_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :server_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :server_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :server_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :server_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :server_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :server_public_ipaddress, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :server_public_ipaddress, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :server_private_ipaddress, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :server_private_ipaddress, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :server_account, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :server_account, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :server_password, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :server_password, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :server_status, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :server_status, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                servers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/servers/edit.html.erb
<%- model_class = Server -%>
<div class="page-header">
  <h2><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h2>
</div>
<%= render :partial => 'form' %>

app/views/servers/index.html.erb
<%- model_class = Server -%>
<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h2>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:customer_name) %></th>
      <th><%= model_class.human_attribute_name(:customer_email) %></th>
      <th><%= model_class.human_attribute_name(:server_name) %></th>
      <th><%= model_class.human_attribute_name(:server_id) %></th>
      <th><%= model_class.human_attribute_name(:server_type) %></th>
      <th><%= model_class.human_attribute_name(:server_public_ipaddress) %></th>
      <th><%= model_class.human_attribute_name(:server_private_ipaddress) %></th>
      <th><%= model_class.human_attribute_name(:server_account) %></th>
      <th><%= model_class.human_attribute_name(:server_status) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @servers.each do |server| %>
      <tr>
        <td><%= link_to server.id, server_path(server) %></td>
        <td><%= server.customer_name %></td>
        <td><%= server.customer_email %></td>
        <td><%= server.server_name %></td>
        <td><%= server.server_id %></td>
        <td><%= server.server_type %></td>
        <td><%= server.server_public_ipaddress %></td>
        <td><%= server.server_private_ipaddress %></td>
        <td><%= server.server_account %></td>
        <td><%= server.server_status %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_server_path(server), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      server_path(server),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_server_path,
            :class => 'btn btn-primary' %>

app/views/servers/new.html.erb
<%- model_class = Server -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/servers/show.html.erb
<%- model_class = Server -%>
<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human.titleize %></h2>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:customer_name) %>:</strong></dt>
  <dd><%= @server.customer_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:customer_email) %>:</strong></dt>
  <dd><%= @server.customer_email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:server_name) %>:</strong></dt>
  <dd><%= @server.server_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:server_id) %>:</strong></dt>
  <dd><%= @server.server_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:server_type) %>:</strong></dt>
  <dd><%= @server.server_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:server_public_ipaddress) %>:</strong></dt>
  <dd><%= @server.server_public_ipaddress %></dd>
  <dt><strong><%= model_class.human_attribute_name(:server_private_ipaddress) %>:</strong></dt>
  <dd><%= @server.server_private_ipaddress %></dd>
  <dt><strong><%= model_class.human_attribute_name(:server_account) %>:</strong></dt>
  <dd><%= @server.server_account %></dd>
  <dt><strong><%= model_class.human_attribute_name(:server_password) %>:</strong></dt>
  <dd><%= @server.server_password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:server_status) %>:</strong></dt>
  <dd><%= @server.server_status %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              servers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_server_path(@server), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              server_path(@server),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>