config/routes.rb
Servermgr::Application.routes.draw do
  resources :servers

  match '/auth/:provider/callback', :via => :get, :to => 'sessions#create'
  match '/auth/failure', :via => :get, :to => 'sessions#failure'
  get 'logout', :to => 'sessions#destroy'
  match 'bad' => 'sessions#bad', :via => :get, :as => :bad

  get 'home' => 'home#index', :as => :home
  get 'about' => 'home#about', :as => :about
  get 'contact' => 'home#contact', :as => :contact

  resources :cloud_accounts
  resources :sessions

  resources :users, :id => /[a-z0-9-]*/

  root :to => 'welcome#index'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Company Cloud Servers</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
      <%= nav_bar :static => :top, :brand => "Server Manager", :brand_link => "http://blog.serverbooter.com" do %>
            <%= menu_group do %>
                <%= menu_item "Home", home_path %>
                <%= menu_divider %>
                <%= drop_down "Action" do %>
                    <%= menu_item "List", servers_path %>
                    <%= menu_item "Create", new_server_path %>
                <% end %>
                <%= menu_item "About Us", about_path %>
                <%= menu_item "Contact", contact_path %>
            <% end %>
            <%= menu_group :pull => :right do %>
                <%= drop_down "#{current_user.first_name} #{current_user.last_name}" do %>
                    <%= menu_item "Edit Profile", edit_user_path(current_user) %>
                    <%= menu_item "Log Out", logout_path %>
                <% end %>
            <% end %>
      <% end %>
<% end %>

<%= yield %>

</body>
</html>